<a href="https://colab.research.google.com/github/DrAyesha91/Nasscom-fdp-/blob/main/hands_on_1%2C2%2C3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#create vector & basic operations
import numpy as np
u=np.array([2,3])
v=np.array([4,1])
print("u+v=",u+v)
print("3*u=", 3*u)

u+v= [6 4]
3*u= [6 9]


In [3]:
#dot product
dot1 = np.dot(u, v)          # 2*4 + 3*1 = 11
dot2 = u @ v                 # Same result

cos_theta = np.dot(u, v) / (
    np.linalg.norm(u) * np.linalg.norm(v)
)

theta = np.arccos(cos_theta)

print(f"Angle: {np.degrees(theta):.1f}°")


Angle: 42.3°


In [5]:
## Norms & Cosine Similarity
w = np.array([3, -4])

print("L1:", np.linalg.norm(w, 1))       # 7.0
print("L2:", np.linalg.norm(w, 2))       # 5.0
print("Linf:", np.linalg.norm(w, np.inf))# 4.0

from sklearn.metrics.pairwise import cosine_similarity

a = np.array([[1, 2, 3]])
b = np.array([[2, 4, 6]])

print(cosine_similarity(a, b))           # [[1.0]]

L1: 7.0
L2: 5.0
Linf: 4.0
[[1.]]


Excercise 1. create 3 vectors representing studetns exam scores in maths science english 2.create L2 norms(overall performance) computer consine similarity between pairs( similar performance patterns?
3. interprret the results?

In [12]:
# 3 vectors students
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Student vectors (Maths, Science, English)
u = np.array([85, 90, 80])
v = np.array([80, 88, 78])
w = np.array([60, 65, 70])
print("L1 (A):", np.linalg.norm(u, 1))        # 255.0
print("L2 (A):", np.linalg.norm(u, 2))        # 142.13
print("Linf (A):", np.linalg.norm(u, np.inf)) # 90.0

print("L1 (B):", np.linalg.norm(v, 1))        # 246.0
print("L2 (B):", np.linalg.norm(v, 2))        # 136.10
print("Linf (B):", np.linalg.norm(v, np.inf)) # 88.0

print("L1 (C):", np.linalg.norm(w, 1))        # 195.0
print("L2 (C):", np.linalg.norm(w, 2))        # 109.54
print("Linf (C):", np.linalg.norm(w, np.inf)) # 70.0
a = np.array([u])
b = np.array([v])
c = np.array([w])

print("A vs B:", cosine_similarity(a, b))   # [[0.9996]]
print("A vs C:", cosine_similarity(a, c))   # [[0.9980]]
print("B vs C:", cosine_similarity(b, c))   # [[0.9975]]

L1 (A): 255.0
L2 (A): 147.39402972983675
Linf (A): 90.0
L1 (B): 246.0
L2 (B): 142.22517358048822
Linf (B): 88.0
L1 (C): 195.0
L2 (C): 112.80514172678478
Linf (C): 70.0
A vs B: [[0.99985014]]
A vs C: [[0.99538069]]
B vs C: [[0.99602768]]


In [14]:
# 🛠️ Hands-On #2: Matrix Operations in NumPy

## Matrix Creation & Basic Ops
import numpy as np

A = np.array([[2, 1], [0, 3]])
B = np.array([[1, 4], [2, 5]])

print("A + B =\n", A + B)
print("A transpose =\n", A.T)
print("A @ B =\n", A @ B)    # Matrix multiplication


A + B =
 [[3 5]
 [2 8]]
A transpose =
 [[2 0]
 [1 3]]
A @ B =
 [[ 4 13]
 [ 6 15]]


In [16]:
## Identity & Inverse
I = np.eye(3)                # 3x3 identity matrix
print("Identity:\n", I)

A = np.array([[2, 1], [1, 3]])
A_inv = np.linalg.inv(A)

print("A inverse:\n", A_inv)
print("A @ A_inv =\n", A @ A_inv)   # Should be identity


Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A inverse:
 [[ 0.6 -0.2]
 [-0.2  0.4]]
A @ A_inv =
 [[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


In [17]:
## Solving Ax = b
# Solve: 2x + y = 5, x + 3y = 7

A = np.array([[2, 1], [1, 3]])
b = np.array([5, 7])

x = np.linalg.solve(A, b)    # More stable than inv(A) @ b

print("Solution:", x)        # [1.6, 1.8]

# Verify: A @ x should equal b
print("Check: A @ x =", A @ x)   # [5.0, 7.0]


Solution: [1.6 1.8]
Check: A @ x = [5. 7.]


# Exercise

1. Create a *3×3 system of equations* from a real scenario (e.g., pricing 3 products given 3 customer orders).
2. Solve using np.linalg.solve().
3. Verify your answer.


In [18]:
import numpy as np

# Product prices: Pen, Notebook, Eraser

A = np.array([
    [2, 1, 3],   # Order 1
    [1, 2, 1],   # Order 2
    [3, 1, 2]    # Order 3
])

b = np.array([19, 13, 20])   # Total costs

prices = np.linalg.solve(A, b)

print("Pen, Notebook, Eraser prices:")
print(prices)

# Verification
print("Check:")
print(A @ prices)

Pen, Notebook, Eraser prices:
[3.75 3.25 2.75]
Check:
[19. 13. 20.]


Hands on 3:identity and inverse in Num

In [21]:
import numpy as np
I= np.eye(3)         # 3x3 identiy matrix
print("Identity:\n", I)
A=np.array([[2,1],[1,3]])
A_inv=np.linalg.inv(A)
print("A inverse:\n", A_inv)
print("A@A_inv=\n",A@A_inv)   #should be identity

Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A inverse:
 [[ 0.6 -0.2]
 [-0.2  0.4]]
A@A_inv=
 [[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]
